server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: web-api
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
